# Generated by Django 4.0.5 on 2022-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.AddField(
            model_name='profile',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='корпус'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.CharField(blank=True, max_length=100, verbose_name='дом'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='почтовый индекс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
