# Generated by Django 4.0.5 on 2022-07-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
