# Generated by Django 4.0.5 on 2022-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rating_review_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=300, verbose_name='Отзыв'),
        ),
    ]
