# Generated by Django 4.0.5 on 2022-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_city_remove_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='корпус'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(blank=True, max_length=100, verbose_name='дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='почтовый индекс'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='улица'),
        ),
    ]
