# Generated by Django 4.0.5 on 2022-07-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_phone_alter_order_apartment_alter_order_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
