# Generated by Django 4.0.5 on 2022-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='корпус'),
        ),
    ]
