# Generated by Django 4.0.5 on 2022-08-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=100, verbose_name='корпус'),
        ),
    ]
